---
fixtures:
  repositories:
    kmod: https://github.com/voxpupuli/puppet-kmod
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    filemapper: https://github.com/voxpupuli/puppet-filemapper
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core
